export { WhatsAppMonitor } from './client.js'
export {
  loadConfig,
  saveConfig,
  addToAllowlist,
  removeFromAllowlist,
  isAllowed,
  getConfigPath,
  getConfigDir,
  resolveNotify,
  NotifyConfigError,
  CONFIG_DIR,
  CONFIG_FILE,
  DEFAULT_AUTH_DIR,
  DEFAULT_NOTIFY_LOG,
} from './config.js'
export type {
  MonitorConfig,
  NotifyConfig,
  ResolvedNotify,
  NotificationPayload,
  GroupInfo,
  ContactInfo,
  GroupMetadata,
  Participant,
  MonitorMessage,
  QuotedMessage,
  MessageType,
  MessageCallback,
  ConnectionState,
  ConnectionCallback,
  QRCallback,
  HistorySyncData,
  HistorySyncCallback,
} from './types.js'
